
INSERT INTO EMPLOYEES VALUES(1, 'Ram', null);
INSERT INTO EMPLOYEES VALUES(2, 'Gopal',1);
INSERT INTO EMPLOYEES VALUES(3, 'Kumar',2);
INSERT INTO EMPLOYEES VALUES(4, 'Ankit',2);
INSERT INTO EMPLOYEES VALUES(5, 'Amar',4);
